Added 'response' event to propagate GraphHopper credit update
perliedman/lrm-graphhopper pull request #16
Opened 2017-05-23 21:30 UTC by opoto

Also upgraded example to leaflet 1.0.3 (and its included dist/leaflet-routing-machine.js URL, please check this is ok)

2017-05-24 07:05 UTC, perliedman requested changes
Looking good! Except for my comment, this looks good to merge!

2017-05-24 07:05 UTC, perliedman commented on src/L.Routing.GraphHopper.js
> +				var fired = err ? err : resp;
I'm thinking this event should only fire if the request hasn't timed out, so move it inside the conditional below. As it is now, you will get `response` events also for timed out requests, which could be confusing, although it's really an edge case.

2017-05-24 17:32 UTC, opoto commented
Good point, I updated as suggested.

2017-05-30 22:51 UTC, opoto commented
Any comment?

2017-05-31 08:16 UTC, merged

2017-05-31 08:17 UTC, perliedman commented
:+1:

2017-05-31 08:19 UTC, perliedman commented
Published a new version, 1.2.0, with this included.